### ISSUE TITLE
need full URL to model link http://pan.baidu.com/s/1i38IAIp

### ISSUE THREAD

**Issue by wajihullahbaig** [guoyilin/FaceDetection_CNN#11]
Sorry guys I am sitting behind a proxy and I need to know if I can get the full URL to download the model.
Anyone kind enough to share the full URL?

**Comment by guoyilin** [comment]
https://pan.baidu.com/s/1pJJ2WKN

**Comment by wajihullahbaig** [comment]
Thanks guoyilin
The problem is that baidu servers donot allow proxies to access them
So if you can upload with Google Share or some other link it will be great!

**Comment by erogol** [comment]
here's the same

**Comment by guoyilin** [comment]
Thanks, @wajihullahbaig, I upload ithe model in google drive: https://drive.google.com/file/d/0B8_dH3SiT7reMjJVRjJDXzJkRDQ/view?usp=sharing

**Comment by wajihullahbaig** [comment]
Yaaay!
 Thanks man!
