### ISSUE TITLE
Request for model from model in Baidu Yun

### ISSUE THREAD

**Issue by Elpidam** [guoyilin/FaceDetection_CNN#8]
Hello! 
I'm having trouble downloading model from Baidu Yun. Could it be possible to redirect me to another link or somehow send it to me?

Thank you in advance

**Comment by mgaueca** [comment]
Hello,

I also have problems downloading the model from Baidu ... Could it be possible to upload it in another place...Thanks !

**Comment by Elpidam** [comment]
Is there anyone who can send me this file?

**Comment by tkietzma** [comment]
Same here, if anyone has the file available, please share.

<update> Baidu link seems to be working again (downloaded using Chrome): http://pan.baidu.com/s/1i38IAIp </update>

**Comment by Elpidam** [comment]
@tkietzma it seems to work. Thank you
